# Generated by Django 4.1.8 on 2023-04-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="alias",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
