# Generated by Django 4.1.8 on 2023-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_url_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="last_clicked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="redirect_count",
            field=models.IntegerField(default=0),
        ),
    ]
